### ISSUE TITLE
DEEPLAB issue

### ISSUE THREAD

**Issue by zzw0812** [nauyan/Segmentation#3] opened 2020-07-28 14:19 UTC
When I use the deeplabv3 model to test, I got this error, can you give some advice?

Traceback (most recent call last):
  File "Test.py", line 26, in <module>
    pred = model.predict(image)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1268, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:1147 predict_function  *
        outputs = self.distribute_strategy.run(
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:1122 predict_step  **
        return self(x, training=False)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:927 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py:719 call
        convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py:888 _run_internal_graph
        output_tensors = layer(computed_tensors, **kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:927 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/layers/merge.py:183 call
        return self._merge_function(inputs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/layers/merge.py:522 _merge_function
        return K.concatenate(inputs, axis=self.axis)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:2709 concatenate
        return array_ops.concat([to_dense(x) for x in tensors], axis)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1606 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py:1189 concat_v2
        "ConcatV2", values=values, axis=axis, name=name)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:595 _create_op_internal
        compute_device)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3327 _create_op_internal
        op_def=op_def)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1817 __init__
        control_input_ops, op_def)
    /data/home/amaxcuda8/.conda/envs/zh_py35/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1657 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimension 1 in both shapes must be equal, but are 16 and 64. Shapes are [?,16,16] and [?,64,64]. for '{{node deeplabv3plus/concatenate/concat}} = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32](deeplabv3plus/lambda_2/resize/ResizeBilinear, deeplabv3plus/aspp0_activation/Relu, deeplabv3plus/activation_70/Relu, deeplabv3plus/activation_72/Relu, deeplabv3plus/activation_74/Relu, deeplabv3plus/concatenate/concat/axis)' with input shapes: [?,16,16,256], [?,64,64,256], [?,64,64,256], [?,64,64,256], [?,64,64,256], [] and with computed input tensors: input[5] = <3>.

**Comment by nauyan** [comment] 2020-07-29 07:09
Can you tell me the input size you are using?

**Comment by zzw0812** [comment] 2020-07-29 07:12
> Can you tell me the input size you are using?

I use the MoNuseg datasets you released

**Comment by zzw0812** [comment] 2020-07-29 07:29
> Can you tell me the input size you are using?

I use the MoNuseg2018 datasets, the training process is normal, but I can't use the trained model to do test, can you give me some advice?

**Comment by nauyan** [comment] 2020-07-29 07:39
Okay I have realized what the problem is. During training, I had set the Input Size to 256x256x3 whereas while Inference I had set them to 1024x1024 so that is why it is not working. So you either have to resize your image to respective input size of model or you could generate tiles for input.

**Comment by zzw0812** [comment] 2020-07-29 07:45
> Okay I have realized what the problem is. During training, I had set the Input Size to 256x256x3 whereas while Inference I had set them to 1024x1024 so that is why it is not working. So you either have to resize your image to respective input size of model or you could generate tiles for input.

Thanks for you quick reply, can you  give me some code example?

**Comment by nauyan** [comment] 2020-07-29 07:50
Have a look at this [Train.py](https://github.com/nauyan/Segmentation/blob/master/Train.py). I have prepared the inputs such as converted 1024x1024 Images to 256x256 Tiles.

**Comment by zzw0812** [comment] 2020-07-31 09:58
> Have a look at this [Train.py](https://github.com/nauyan/Segmentation/blob/master/Train.py). I have prepared the inputs such as converted 1024x1024 Images to 256x256 Tiles.

It's a interesting work, but I hope you can update your code. Till to now, we can't use the model(like SEGNET/DEEPLAB/UNTMOD) to do testing, that's a pity.

**Comment by nauyan** [comment] 2020-08-03 16:54
I will update the code by the end of this week.

**Comment by nauyan** [comment] 2020-08-07 08:41
@zzw0812 Thank you for your feedback I have updated the repo and fixed inference errors. Run the code and let me know if there is any issue.

**Comment by zzw0812** [comment] 2020-08-07 14:25
> @zzw0812 Thank you for your feedback I have updated the repo and fixed inference errors. Run the code and let me know if there is any issue.

Thanks for your update, I have leraned a lot from the code. I'll test the code next and give you feedback. Thanks!

**Comment by nauyan** [comment] 2020-08-07 14:38
I am glad that my code has helped you.

**Closed** 2020-08-11 11:55 UTC
